services:
  - type: web
    name: civicspot-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    rootDir: ./frontend
    envVars:
      - key: VITE_MAPBOX_TOKEN
        value: pk.eyJ1IjoieWF4aGh1YiIsImEiOiJjbWN5OWY4YnAwa2lrMnJxeGtpd2VwaG40In0.ZUAgUVKLyEeN9DLoY603tA
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com